// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXHztF9Hldv_KDXYV7ffedcoyDLjy46l8',
    appId: '1:217435102298:web:c6ac6068b5c182fb0fcc63',
    messagingSenderId: '217435102298',
    projectId: 'neutron-pms',
    authDomain: 'neutron-pms.firebaseapp.com',
    storageBucket: 'neutron-pms.appspot.com',
    measurementId: 'G-W6KMLV6XGN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYc-ohEVW-SXCsFwxXX0DtiEfD1x6MSPg',
    appId: '1:217435102298:android:c5459ef768b82bf10fcc63',
    messagingSenderId: '217435102298',
    projectId: 'neutron-pms',
    storageBucket: 'neutron-pms.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF980ZinR7Eba9PrMHPYho7NxvY-GAx6Y',
    appId: '1:217435102298:ios:120f88a819ed9ece0fcc63',
    messagingSenderId: '217435102298',
    projectId: 'neutron-pms',
    storageBucket: 'neutron-pms.appspot.com',
    androidClientId:
        '217435102298-shi8ioef2aupghdj4617tda20eefsh3t.apps.googleusercontent.com',
    iosClientId:
        '217435102298-dmt90c1rmhmkojjfbur5stldu5065kn5.apps.googleusercontent.com',
    iosBundleId: 'com.example.ihotel',
  );
}
